// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7DtYQKc2NQqjCjNpcvpA0ZgwPq3PXWOs',
    appId: '1:667490620610:web:600e8041dc11b19483975b',
    messagingSenderId: '667490620610',
    projectId: 'pushnotif-78183',
    authDomain: 'pushnotif-78183.firebaseapp.com',
    storageBucket: 'pushnotif-78183.appspot.com',
    measurementId: 'G-R0FQN0HL0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK7pog7CU-RghqgJW9NTfoicOZEidYmIU',
    appId: '1:667490620610:android:924ef991ea2d46d183975b',
    messagingSenderId: '667490620610',
    projectId: 'pushnotif-78183',
    storageBucket: 'pushnotif-78183.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhsD-eWy9uLDVlViLOKUWMSjXxqNu8xng',
    appId: '1:667490620610:ios:bb0dc879a378ffd783975b',
    messagingSenderId: '667490620610',
    projectId: 'pushnotif-78183',
    storageBucket: 'pushnotif-78183.appspot.com',
    iosClientId: '667490620610-klg9or3kooocovn2hiufslq82eg357pe.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
